targets:
  $default:
#    sources:
#      include:
#        - "lib/sass/**"
    builders:
      sass_builder:
#        generate_for:
#          include:
#            - "sass/**/*.scss"
#          exclude:
#            - "sass/**/*_.scss"
        options:
          outputStyle: compressed
