name: bootstrap
version: 4.0.0
description: Bootstrap's files, in a pub package. Contains
             Bootstrap 4.0.0
             Included is a transformer to swap the CSS for a CDN version.
authors:
- Bootstrap core team
- Victor Berchet <victor@suumit.com>
- Seth Ladd <sethladd@gmail.com>
- Richer Larivière <richerlariviere@gmail.com>

environment:
  sdk: '>=1.22.1 <3.0.0'

homepage: https://github.com/richerlariviere/bootstrap_for_pub

dependencies:
  build: any
  build_runner: any
  dart2_constant: ^1.0.0
  sass_builder: any
  sass: any
#  barback: ">=0.14.1+3 <0.16.0"
#  html: ">=0.12.0 <0.14.0"

